version: "3.8"

services:
  app:
    image: node:16.6.0
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    working_dir: "/usr/src/app"
    command: "npm run start:dev"
    env_file:
      - .env
  db:
    image: postgres:15
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
